import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';


const TermsAndConditions: React.FC = () => {
  return (
      <main className="flex-grow flex items-center justify-center p-6">
        <Card className="w-full max-w-4xl shadow-2xl">
          <CardHeader className=" border-b">
            <CardTitle className="text-3xl font-bold text-black-800">
              Terms and Conditions
            </CardTitle>
          </CardHeader>
          <CardContent className="p-8">
            <div className="space-y-8 text-lg text-gray-700">
              <section>
                <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
                <p>
                  Welcome to LegalGPT. By accessing or using our service, you agree to these Terms and Conditions.
                  Please read them carefully before using our platform.
                </p>
              </section>

              <Separator className="my-6" />

              <section>
                <h2 className="text-2xl font-semibold mb-4">2. Service Usage</h2>
                <p>
                  2.1 LegalGPT provides AI-powered legal assistance and document generation services.
                </p>
                <p>
                  2.2 You agree to use the service for lawful purposes only and not to:
                </p>
                <ul className="list-disc list-inside ml-6 mt-2">
                  <li>Violate any applicable laws</li>
                  <li>Infringe on intellectual property rights</li>
                  <li>Engage in fraudulent activities</li>
                </ul>
              </section>

              <Separator className="my-6" />

              <section>
                <h2 className="text-2xl font-semibold mb-4">3. Intellectual Property</h2>
                <p>
                  3.1 All content generated by LegalGPT remains the property of the user, subject to our usage terms.
                </p>
                <p>
                  3.2 LegalGPT retains the right to use anonymized data for service improvement.
                </p>
              </section>

              <Separator className="my-6" />

              <section>
                <h2 className="text-2xl font-semibold mb-4">4. Limitation of Liability</h2>
                <p>
                  4.1 LegalGPT provides services "as is" and does not guarantee absolute accuracy of legal documents.
                </p>
                <p>
                  4.2 Users are advised to consult with a qualified legal professional for critical legal matters.
                </p>
              </section>

              <Separator className="my-6" />

              <section>
                <h2 className="text-2xl font-semibold mb-4">5. Privacy</h2>
                <p>
                  5.1 Your use of LegalGPT is also governed by our Privacy Policy.
                </p>
                <p>
                  5.2 We are committed to protecting your personal and legal information.
                </p>
              </section>

              <Separator className="my-6" />

              <section>
                <h2 className="text-2xl font-semibold mb-4">6. Termination</h2>
                <p>
                  6.1 LegalGPT reserves the right to terminate or suspend accounts that violate these terms.
                </p>
                <p>
                  6.2 Users may terminate their account at any time by contacting our support team.
                </p>
              </section>
            </div>
          </CardContent>
        </Card>
      </main>
  );
};

export default TermsAndConditions;
